theme: jekyll-theme-minimal
title: CSE 15L Software Tools and Techniques Lab
description: UCSD Winter 2022\n\nhttps://www.nicepng.com/png/detail/209-2095181_jacobs-school-of-engineering-logo-downloads-uc-san.png